### ISSUE TITLE
Dart not accepting files

### ISSUE THREAD

**Issue by cfidler** [APTrust/dart#476]
While adding files from a CD-R, DART flagged two files with messages saying that they were already added to the package as part of a different file. I've added a screenshot. These are two completely different files - the files are missing their extensions but they are psd files. It drops them from the bag.
 
![image](https://user-images.githubusercontent.com/4007724/128571603-b63b9539-a3f3-4e84-b62d-d9427fca83cd.png)

**Comment by diamondap** [comment]
Thanks. I'll take a look.

**Comment by diamondap** [comment]
Can you try installing the new version 2.0.12? That should fix the issue. The download links are listed at https://aptrust.github.io/dart-docs/download/.

Let me know if this solves the problem.

**Comment by cfidler** [comment]
Thank you. I updated DART but am still having issues but I noticed it was with different files:

![screenshot_p2019086](https://user-images.githubusercontent.com/4007724/129954012-7cb1b26c-37f0-4c84-aa45-c7785c656d50.JPG)

**Comment by diamondap** [comment]
OK. I'll take another look.

**Comment by diamondap** [comment]
I cannot reproduce this on Mac or Windows. I built a directory containing files with the same names and had no trouble bagging. It's odd that the validator says the files are in the manifest but missing from the payload directory, then says the same files are in the payload directory but not the manifest.

DART keeps job information intact even after you upgrade to a new version. Your job was probably defined in the older 2.0.11 version, which had trouble with some file names. Try deleting the job and recreating it from scratch. 

- Go to **Jobs > List**
- Click the name of the job
- Click the red **Delete** button in the bottom left corner

Then create a new job, drag the files back in and continue. Let me know what happens.

**Comment by cfidler** [comment]
I deleted the jobs but it is still not packaging. I believe there are corrupted files on the disk. Bagger was also unable to bag the files, and it also flagged down the same 'Jan and Mon' file. These are PSD images from 2003. I was able to image the disk and I extracted the identified file but it opens without issue in Photoshop. I also ran a file check on that file but it didn't find anything, but clearly there is something in these files that is tripping up the process.
